# Generated by Django 5.2.8 on 2025-11-21 16:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=9, unique=True, verbose_name='NIF')),
                ('designacao_social', models.CharField(max_length=200)),
                ('designacao_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('morada', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['designacao_social'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('designacao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['designacao'],
            },
        ),
        migrations.CreateModel(
            name='TipoControlador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Controlador',
                'verbose_name_plural': 'Tipos de Controladores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('user', 'User'), ('viewer', 'Viewer')], default='user', max_length=20)),
                ('tipo_empresa', models.CharField(choices=[('tecnimpor', 'Tecnimpor (Interno)'), ('cliente', 'Cliente')], default='tecnimpor', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['marca', 'nome'],
                'unique_together': {('marca', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ModeloControlador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelo')),
            ],
            options={
                'verbose_name': 'Modelo + Controlador',
                'verbose_name_plural': 'Modelos + Controladores',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, verbose_name='Número de Série')),
                ('notas', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='core.cliente')),
                ('modelo_controlador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modelocontrolador')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['cliente', 'numero_serie'],
                'unique_together': {('modelo_controlador', 'numero_serie')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pais'),
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=12, unique=True, verbose_name='Senha (12 caracteres)')),
                ('tipo', models.CharField(choices=[('definitiva', 'Definitiva'), ('temporaria', 'Temporária')], default='definitiva', max_length=15)),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em_data', models.DateField()),
                ('criado_em_hora', models.TimeField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senhas_criadas', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senhas', to='core.equipamento')),
            ],
            options={
                'verbose_name': 'Senha',
                'verbose_name_plural': 'Senhas',
                'ordering': ['-criado_em_data', '-criado_em_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição')], max_length=20)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('senha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.senha')),
            ],
            options={
                'verbose_name': 'Histórico de Senha',
                'verbose_name_plural': 'Históricos de Senhas',
                'ordering': ['-data', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='VersaoControlador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=50)),
                ('tipo_controlador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipocontrolador')),
            ],
            options={
                'verbose_name': 'Versão de Controlador',
                'verbose_name_plural': 'Versões de Controladores',
                'ordering': ['tipo_controlador', 'versao'],
                'unique_together': {('tipo_controlador', 'versao')},
            },
        ),
        migrations.AddField(
            model_name='modelocontrolador',
            name='versao_controlador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.versaocontrolador'),
        ),
        migrations.AlterUniqueTogether(
            name='modelocontrolador',
            unique_together={('modelo', 'versao_controlador')},
        ),
    ]
