# Generated by Django 5.2.8 on 2025-11-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontrolador',
            name='tipo_senha',
            field=models.CharField(choices=[('alfanumerica', 'Alfanumérica (Letras + Números)'), ('numerica', 'Numérica (Apenas Números)')], default='alfanumerica', help_text='Define se o controlador aceita senhas alfanuméricas ou apenas numéricas', max_length=15, verbose_name='Tipo de Senha Permitida'),
        ),
    ]
